### ISSUE TITLE
Menu item icon color not showing

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1003]
Hi,

When I open select icon color not showing

![image](https://github.com/smartstore/Smartstore/assets/20780272/c4a6343f-7412-42d2-9f35-1e766e23274e)

![image](https://github.com/smartstore/Smartstore/assets/20780272/f6f3f593-2dee-428e-ab35-93d40e793e77)

**Comment by suatsuphi** [comment]
> Can't be reproduced

what do you mean ? I downloaded the project from github and installed it, but the color boxes do not appear.

**Comment by Michael-Herzog** [comment]
Thanks for being persistent on this issue! I've tested the current branch as well as the latest stable release branch here on my local machine and could not reproduce the problem. Now I found out this has something to do with a PageBuilder script, which always  ran on my machine and made the problem unreproducable for me. We're on it. Should be fixed with the next release.

**Comment by suatsuphi** [comment]
thanks its working now


https://github.com/smartstore/Smartstore/commit/e59152aa9e3309b0bb976443582b8a6369a55169

**Comment by suatsuphi** [comment]
option.select2();

$('.icon-color-chooser > option').select2();

If select2 is updated, the color of the selected one also appears. had to call select2() twice

```
<script sm-target-zone="scripts" data-origin="menu-item-create-or-update">
    $(function () {
        // Icon colors.
        const colorVars = Smartstore.Admin.getThemeColorVars();
        $('.icon-color-chooser > option').each(function () {
            var option = $(this);
            option.data("color", colorVars['--' + this.value]);
            option.select2();
        });
        $('.icon-color-chooser > option').select2();
    });
</script>
```
