### ISSUE TITLE
model.MetaProperties.ImageUrl  Image address problem

### ISSUE THREAD

**Issue by AtlantisDe** [smartstore/Smartstore#1047]
**Model**

```c#
ProductDetailsModel 
```

**Attribute**

```c#
model.MetaProperties.ImageUrl
```

**Test In**

```c#
src/Smartstore.Web/Controllers/ProductController.cs

//ProductDetails
 public async Task<IActionResult> ProductDetails(int productId, ProductVariantQuery query)
 {

            model.MetaProperties = await model.MapMetaPropertiesAsync();

            model.MetaProperties.ImageUrl = model.MetaProperties.ImageUrl.Replace("http://localhost", "");


```

**problem**
![image](https://github.com/smartstore/Smartstore/assets/39150678/917a3fe4-aa1c-4e65-bc20-8d5b1f4fadaa)

 
1. Get the image address, incorrect
 
```c#

http://localhost/media/8/catalog/TikTok.png

//The reverse proxy I actually use uses a public domain name

//The relative address should be obtained, for example

/media/8/catalog/TikTok.png

```

**Test configuration**

![image](https://github.com/smartstore/Smartstore/assets/39150678/dc6b1187-2618-455d-98ed-5c3dbbd785ff)

- This configuration still does not result in correct results

**Comment by Michael-Herzog** [comment]
Hi,

please explain why this is a problem. This was implemented like this by design. 
The responsible code can be found [here](https://github.com/smartstore/Smartstore/blob/bdca959f4d61a5d806234a7b939459c23595822f/src/Smartstore.Web.Common/Models/Common/Mappers/MetaPropertiesMapperBase.cs#L54)

`imageUrl = WebHelper.GetAbsoluteUrl(imageUrl, request, true);`

When an URL is posted to a social media platform it needs the complete URL in order to request the image. 

Regards,
Michael
