### ISSUE TITLE
Product: are extended attributes supported? Currently specification attributes only supports presets.

### ISSUE THREAD

**Issue by AtlantisDe** [smartstore/Smartstore#1048]
**extended attributes**
Product,Are extended attributes supported?  Currently Specification Attributes only supports presets

**Want to implement properties**
- Attributes can be filled with any value
- This requirement arises when a certain field attribute requires different values. Rather than a very standardized attribute value.

**Comment by mgesing** [comment]
For specification attributes any values can be stored via the backend. If the buyer is to enter any value, then specification attributes are the wrong entity. Product attributes of type textbox or multiline textbox are suitable for this.

**Comment by AtlantisDe** [comment]
In fact, the core function is equivalent to adding a new field, such as string type, product, and any information can be entered. This is a product attribute. It is not input by the customer.

**Comment by stefanmuellerdo** [comment]
Hello AtlantisDe. Please describe your *use-case*. Thank you.

**Comment by AtlantisDe** [comment]
Hello @stefanmuellerdo I hope to support the dynamic input text box type, because some are not standard attributes and need to enter custom text. Because there is too much text, it is impossible to standardize the attributes. Therefore, it is just an input value.


- **Hope to support: custom string text, input attributes.**


![image](https://github.com/smartstore/Smartstore/assets/39150678/fe7cc889-d289-49a2-9f06-cd0b5dce30a8)

**Comment by stefanmuellerdo** [comment]
@AtlantisDe for a real-live use case please provide a full example how a product spec should look, with a sample product.

As I read it, you want a **freetext option** for the Smartstore Specification Attributes. So that you can add something to "4 GB" like: "but built in a special way" on the fly? 

That seems to go against the way Specification Attributes work now in Smartstore. They are used to allow filtering of product searches by Store users, to allow comparisons of products selected by the user. For this to work well, you need clean data. If each product has its own specification, no comparison is possible.

What I could imagine you could work on: A possibility for the shop operator to writeout extra text on the specification attributes individually per-product or perhaps even overwrite the displayed value. Also a hierarchy, i.e. a grouping. Especially with long lists of specification attributes, it would be nice to be able to have more structure: headings and groups.

**Comment by mgesing** [comment]
What is the advantage of this? You have to enter the value somewhere anyway. Whether this happens at the specification attribute options or via the attribute assignment for the product makes not really a difference.

I know a store that also has specification attributes with lots of options. It managed them by spreading them over several attributes and standardized the options as much as possible to limit their number.

If that is not enough, then you would have to enable free text that is displayed on the product detail page together with the specification attributes, but which is not created and saved as a specification attribute
(because, strictly speaking, it is not a specification attribute anymore).

**Comment by AtlantisDe** [comment]
Yes, this does violate the Specification Attributes design. 

it is not a specification attribute.

It's more like an extension property.

The current design plan is to add a table,
Product ID and attribute columns are enough.


So this is temporarily closed. Thank you.
