### ISSUE TITLE
CTRL+F5 - Start Without Debugging not working when changes are made in the Razor (cshtml)

### ISSUE THREAD

**Issue by suatsuphi** [smartstore/Smartstore#1070]
Hi,

CTRL+F5 - Start Without Debugging not working when changes are made in the Razor (cshtml) 

I get the following error.  
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.9.6

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
Generated Code
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.

The type or namespace name 'Razor' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)

**Comment by Algorithman** [comment]
That's probably just an issue with VS2022.
After the last update I had to embed a library for timezone conversion (TZConvert, had it added via nuget) since I got the same error.
Odd thing is it worked just fine before updating and I didn't make any changes to this part.

**Comment by muratcakir** [comment]
Most likely caused by missing `ICompilationReferencesProvider` implementation for the host.

**Comment by muratcakir** [comment]
`RazorCompileOnBuild` is already defined in [Smartstore.Razor.props](https://github.com/smartstore/Smartstore/blob/main/src/Smartstore.Build/Smartstore.Razor.props) and conditionally turns off razor build compilation. So your fix is not a solution, because runtime compilation is broken and you have just turned it off.

Side note: If you select the build configuration `DebugNoRazorCompile` you will get the same result.
