### ISSUE TITLE
Unhandled AccessDeniedException when editing customer roles

### ISSUE THREAD

**Issue by bandieramonte** [smartstore/Smartstore#1117]
**Describe the bug**
When an admin who does not have the permission to edit customer roles, still tries to edit it, then when clicking the save button when changing any customer role would throw user this screen:
![image](https://github.com/smartstore/Smartstore/assets/25406999/f5369388-6075-4fa7-9493-8306476b2d4c)

**To Reproduce**
1. As an admin, create a customer role that provides permissions to read customer roles, but not to edit them.
2. Create a new customer with the customer role just created in the previous step.
3. Log in as that new customer, and try to edit any customer role, clicking the Save button after changing any item from the Access Control List page of any customer role. 
4. An unhandled exception, as shown in the image above, would blow up on the interface.

**Expected behavior**
Instead of blowing into that screen with an unhandled exception, simply show a red message, maybe in the lower right corner, indicating that the logged in user has no permission to edit any customer role. 

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro x64
 - Browser: Chrome version 125.0.6422.141 (Official Build) (64-bit)

**Additional context**
Using Smartstore 5.1,  branch 'main' updated as of the date this issue was posted.

**Comment by bandieramonte** [comment]
Actually this unhandled exception of this type seems to appear when user tries to do anything it is not authorized to do in the dashboard.

**Comment by mgesing** [comment]
This is the expected behavior. The screenshot shows the full stack trace that is displayed by default in developer mode.
To change this, the following must be added to the **Smartstore** node in **appsettings.Development.json** file

`"UseDeveloperExceptionPage": false,`

For the production environment, the setting is made in the **appsettings.json** file. As a result, instead of the stack trace, an access denied notification appears with the name of the permission that is not granted.

**Comment by bandieramonte** [comment]
Thank you, I tested the way as you explained and it works as you explained. Now I know about this functionality. 
I apologize for posting a bug when it wasn't.
