### ISSUE TITLE
Google Merchant Centre - Bundle / Grouped Products

### ISSUE THREAD

**Issue by OGExclusives** [smartstore/Smartstore#1138]
When ticking the option within your module to output all combinations for the product, if the product is a bundle or a grouped product. Google merchant center doesn't split these and output each viable combination, only a single product. This hurts the listing availability. 

Ideally, ticking the combination option should calculate all possible combinations of the bundled products options and merge into one like a standard combination for the feed.

**Comment by mgesing** [comment]
The option **Export attribute combinations** is used to export product variants as individual products. It has nothing to do with group products or bundles because they do not have variants. Associated products of a grouped product are exported as individual products if **Do not export grouped products** is activated. Bundled products are exported depending on their visibility setting.
