### ISSUE TITLE
Ajaxify product tag selection in backend

### ISSUE THREAD

**Issue by muratcakir** [smartstore/Smartstore#388]

**Comment by mgesing** [comment]
Loading via AJAX is not good here. There is no search field multiple tags select2 box. If you type something, the input automatically appears at the first position in the popup list and clicking on it will add it as a new tag. An "Enter" does not (!) apply the entry, but removes it again (not very intuitive). Hard to explain.

Better and easier: just load e.g. a maximum of 5000 product tags instead of all. The user won't want to search in such a long list anyway, but will simply enter missing tags directly. Product tags are stored by IProductTagService.UpdateProductTagsAsync and this method ensures that no duplicate tags are stored anyway.
