### ISSUE TITLE
Web API: OData Connected Service creates wrong auto-generated code for API clients

### ISSUE THREAD

**Issue by mgesing** [smartstore/Smartstore#389]
Examples: it incorrectly generates FileItemInfoSingle instead of IEnumerable<FileItemInfo> as return value for GET /MediaFiles/GetFilesByIds(Ids=[1,2,3]) and it often uses the wrong HTTP method (GET instead of POST) which will result in a 404...

All OData actions and functions must be checked and tested with regard to their configuration to see whether an auto-generated code generator translates it correctly.

**Comment by mgesing** [comment]
ODataModelBuilder always reverts back to _Default_ namespace if we choose to set it to null. As a result, Microsoft.OData.Client generates wrong code with wrong URLs including _Default_ for action methods, e.g. `_source.AppendRequestUri("Default.CalculatePrice")`. The user is forced to build the code himself. Example:

```
// Not working:
var price = await container.Products.ByKey(123).CalculatePrice(false, 1, 0, 0).GetValueAsync();

// Working:
var query = new DataServiceActionQuerySingle<CalculatedProductPrice>(container, "http://localhost:59318/odata/v1/Products(123)/CalculatePrice", new BodyOperationParameter("forListing", false));
var price = await query.GetValueAsync();
```

**Comment by Algorithman** [comment]
The problem is in the T4 templates the client generator uses.

Won't work without making some small changes to the T4 templates of the odata client creator. But doable since then we can also exclude System.Net.Http and Microsoft.AspNetCore.Http namespaces from creating the unnecessary and erroneous types (IFormFile, IFormFileCollection, StreamContent and one type from nuget namespace?)
Just search for `"<# fullNamespace #>.`  (including the " and .)
Doesn't appear to often and only twice in conjunction with the AppendRequestUri iirc.

But even with all these changes, I still can't upload a file (MediaFiles.SaveFile). Always getting NRE's :(

**Comment by Algorithman** [comment]
See also https://github.com/OData/odata.net/blob/a526a32fa9abff76aa09b5806700110f9bad5485/src/CodeGen/ODataT4CodeGenerator.ttinclude#L4153

Not possible to remove the namespace from the AppendRequestUri call

**Comment by mgesing** [comment]
https://github.com/OData/odata.net/issues/1396

**Comment by mgesing** [comment]
Closed. I don't see any way to influence this from the Web API plugin. However, if there is a way, please feel free to reopen this issue.
