### ISSUE TITLE
Page Builder: block does not take new position in story editor

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#438]
**Page Builder:** block does not take new position in story editor. Version 4.1.1 (Smartstore Demo Shop)

Bug: block _does not take new position_ in story editor.

Expected: the block stays at its position where we placed it on the story grid

Only in the Brave Browser it works as expected.

(see video)

First Chrome, Second part: Brave

https://user-images.githubusercontent.com/54363171/136010376-80b7da5c-49ef-4e38-bada-2ee8b1c63b1c.MP4

**Comment by stefanmuellerdo** [comment]
better video

https://user-images.githubusercontent.com/54363171/136012202-deceaa66-a8d0-4ef0-a909-3d63ff1a3b7a.mp4

**Comment by zihniartar** [comment]
Cannot be reproduced.

**Comment by zihniartar** [comment]
It turns out that the error only occurs when the demo backend is opened via the live demo page on our homepage. This page uses an iFrame to make the demo backend responsive. Unfortunately, the use of the iFrame causes such inconvenience.

However, this does not mean that the function in Smartstore is buggy or limited.
