### ISSUE TITLE
Payment problem in Checkout for Guest customers (v4.1.1)

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/Smartstore#496]
**Describe the bug**
**Guest** customer orders in the store, at payment method the selected payment method does not work, the customer can then not select another payment method. e.g. At Paypal "Cancel and back", then goes to the order detail page in the frontend, 

**Expected behavior**
After canceling with Paypal, for example, you come back to the checkout page "Select payment method" to select a new payment method.

This has been reported by a CH B2C retailer. Version 4.1.1.

**Comment by mgesing** [comment]
Which PayPal payment method? PLUS, Direct, Express or Standard?

**Comment by meister-dev** [comment]
PayPal Standard

**Comment by mgesing** [comment]
In Smartstore 4.x, PayPal Standard is an old implementation, where the buyer is redirected to PayPal _after_ order placement. You cannot redirect back to the checkout there, because the order is already placed and the shopping cart is empty. The buyer can restart the PayPal payment via his frontend order page if the payment is cancelled, but he can no longer select another payment method.

In SmartStore 5, PayPal is newly implemented, including the desired behaviour described above.

**Comment by meister-dev** [comment]
Will this also be implemented for the Postfinance Plugin with SmartStore 5? We have the same behavior with this payment method.

**Comment by stefanmuellerdo** [comment]
this issue will be discussed
