### ISSUE TITLE
Out-of-Stock products locate at the end of the list

### ISSUE THREAD

**Issue by munkerjs** [smartstore/Smartstore#825]
Hello,

In total, over 5000 products are listed on the site. In the category list, products that are out of stock are at the top of the list and it is not a pleasant sight.

We want to show these products at the end of the category list. We did not see an option for this in the administration panel.

![image](https://github.com/smartstore/Smartstore/assets/32327426/3d4862f9-2995-4f87-b1df-e78de6431a0c)

Since we use premium MegaSearch and MegaSearch Plus plugins, we cannot intervene in the rankings.
How can we do this?

Sample Link: [https://istekirtasiye.com/teknoloji-urunleri/](https://istekirtasiye.com/teknoloji-urunleri/)

**Comment by mgesing** [comment]
This is not possible out-of-the-box. For the availability of products, we have a filter that can be activated in the search settings. This also includes an option for how the filter should behave in the frontend. This way, unavailable products can be visible or hidden by default.

**Comment by erdalp** [comment]
Hello, companies in Turkey that utilize the smartstore infrastructure are on the rise. Unfortunately, this is an existing practice in Turkey. Companies want to display products even if they are out of stock. It is crucial in this country for consumers to see products that will return to stock, even if they are currently out of stock. Store owners prefer these products to appear at the end of the listings because users tend not to proceed further when they encounter out-of-stock items in a list. In the current megasearch plugin, these items can sometimes appear at the beginning of the product listings. If stock availability is checked at the beginning of the process, and products without stock are moved to the last page of the listings, this issue can be resolved.

**Comment by armohamm** [comment]
Hi All,

I think based on below comment, making this checked in option for
availability by default to true should solve the problem, those who prefer
the existing behavior can still uncheck that option, additionally, better
to give this settings for admins as an options.

---
If stock availability is checked at the beginning of the process, and
products without stock are moved to the last page of the listings, this
issue can be resolved.

Best Regards,
Abdul Rahiman
DevOps Automation Engineer
***@***.***

**Comment by mgesing** [comment]
Added a new MegaSearch setting to achieve this.
