### ISSUE TITLE
Email template includes are not read from theme module folder but from Flex

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#849]
**Describe the bug**
The email template includes are not read from the chosen theme's folder.
In `LiquidTemplateEngine.cs` GetTemplate method fs is pointing to my theme:
![image](https://github.com/smartstore/Smartstore/assets/2128945/cd6b6a56-b3b2-4664-9e18-10df4e2bf0dd)

As you see here, file is pointing to "Flex/Views/Shared/EmailTemplates/address.liquid" and my theme "WBlue" is chosen as the file system.

**To Reproduce**
1. Create a theme module (based on Flex)
2. Copy over the email template includes and change something in them
3. Trigger emails with the includes
4. See original include used

**Expected behavior**
LiquidTemplateEngine should use the files inside the chosen theme.

**Desktop (please complete the following information):**
 - OS: linux, win10

**Comment by muratcakir** [comment]
Seems to be a memory cache problem due to insufficient invalidation. Line 97 should contain the whole physical path to the template file, not just the relative path. In line 110, the watcher then _tries_ to monitor a not yet existing file (in your theme folder), which fails: `NullChangeToken` is passed as expiration token. I write this only to let you know... after a fresh restart everything should work fine.

We will refactor the code accordingly.

https://github.com/smartstore/Smartstore/blob/513abf8cbe53cc83a28964d5f126fd3f9c892a5c/src/Smartstore.Core/Platform/Templating/Liquid/LiquidTemplateEngine.cs#L89-L115

**Comment by Algorithman** [comment]
That's the problem, it was after a fresh restart.
But I look into the fs.Watch(path) call, maybe I can figure out why it doesn't want to find my file.

**Comment by muratcakir** [comment]
> But I look into the fs.Watch(path) call, maybe I can figure out why it doesn't want to find my file

With the fix I made (85e81df), it **will** find your file.
