### ISSUE TITLE
[Question] How do i create a controller with localized routes?

### ISSUE THREAD

**Issue by Algorithman** [smartstore/Smartstore#926]
**Is your feature request related to a problem? Please describe.**
We have a custom controller for our spare parts order form which we would like to have localized url routes.
It should be reachable from /Ersatzteile (german), /en/spareparts (english) and /fr/piecesdetachees (french).
I've seen the LocalizedRoute attribute, but how do I register the different routes to each languages so Url.Action also returns the localized url?

Can you give me a quick rundown please? Since the developer guide doesn't have anything about it (yet).

**Comment by muratcakir** [comment]
Unfortunately, this is currently not possible without further effort. This is because LocalizedRouteAttribute fulfils a different purpose: it simply tells the framework that the given URL may or may not have a language prefix (according to current SEO settings).

You would have to build something of your own.

**Comment by Algorithman** [comment]
Oh, i was misled by the name :)
I was looking and looking where the route would be localized :)
Thanks for the info.
